final deploy

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -32,20 +32,26 @@ jobs:
     - name: Get EC2 public IP
       id: get_ec2_ip
       run:  |
-        IP=$(terraform output -raw ec2_user_public_ip || echo "")
-        if [ -z "$IP" ]; then
-          echo "Failed to get EC2 IP"
+         RAW_OUTPUT=$(terraform output -raw ec2_user_public_ip 2>/dev/null)
+         IP=$(echo "$RAW_OUTPUT" | grep -oE '([0-9]{1,3}\.){3}[0-9]{1,3}')
+    
+         if [ -z "$IP" ]; then
+          echo "Failed to get a valid IP address from Terraform output"
           exit 1
-        fi
-        echo "ec2_ip=$IP" >> $GITHUB_OUTPUT
+          fi
+    
+          echo "ec2_ip=$IP" >> $GITHUB_OUTPUT
     - name: Get Ubuntu Public IP   
       id: get_ubuntu_ip
       run: |
-        IP=$(terraform output -raw ubuntu_user_public_ip || echo "")
+        RAW_OUTPUT=$(terraform output -raw ubuntu_user_public_ip 2>/dev/null)
+        IP=$(echo "$RAW_OUTPUT" | grep -oE '([0-9]{1,3}\.){3}[0-9]{1,3}')
+
         if [ -z "$IP" ]; then
-          echo "Failed to get Ubuntu IP"
-          exit 1
+        echo "Failed to get a valid Ubuntu IP address from Terraform output"
+        exit 1
         fi
+
         echo "ubuntu_ip=$IP" >> $GITHUB_OUTPUT
   ansible_deploy:
     runs-on: ubuntu-latest
