error

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -1,9 +1,8 @@
-
 name: Deploy with Terraform and Ansible
 
 on:
   push:
-    branches: 
+    branches:
       - sample
   workflow_dispatch:
 
@@ -11,81 +10,67 @@ jobs:
   terraform_apply:
     runs-on: ubuntu-latest
     outputs:
-      ec2_ip: ${{steps.get_ec2_ip.outputs.ec2_ip}}
-      ubuntu_ip: ${{steps.get_ubuntu_ip.outputs.ubuntu_ip}}
+      ec2_ip: ${{ steps.get_ec2_ip.outputs.ec2_ip }}
 
     steps:
-    - name: Checkout Repo
-      uses: actions/checkout@v3
+      - name: Checkout Repo
+        uses: actions/checkout@v3
 
-    - name: Setup Terraform
-      uses: hashicorp/setup-terraform@v2
+      - name: Setup Terraform
+        uses: hashicorp/setup-terraform@v2
 
-    - name: Terraform Init
-      run: terraform init
+      - name: Terraform Init
+        run: terraform init
 
-    - name: Terraform Apply
-      env:
-        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
-        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
-        AWS_REGION: us-east-1
-      run: terraform apply -auto-approve
+      - name: Terraform Apply
+        env:
+          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
+          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
+          AWS_REGION: us-east-1
+        run: terraform apply -auto-approve
 
-    - name: Get EC2 public IP
-      id: get_ec2_ip
-      run:  |
-         RAW_OUTPUT=$(terraform output -raw ec2_user_public_ip 2>/dev/null)
-         IP=$(echo "$RAW_OUTPUT" | grep -oE '([0-9]{1,3}\.){3}[0-9]{1,3}')
-    
-         if [ -z "$IP" ]; then
-          echo "Failed to get a valid IP address from Terraform output"
-          exit 1
+      - name: Get EC2 public IP
+        id: get_ec2_ip
+        run: |
+          RAW_OUTPUT=$(terraform output -raw ec2_user_public_ip 2>/dev/null)
+          IP=$(echo "$RAW_OUTPUT" | grep -oE '([0-9]{1,3}\.){3}[0-9]{1,3}')
+
+          if [ -z "$IP" ]; then
+            echo "Failed to get a valid IP address from Terraform output"
+            exit 1
           fi
-    
+
           echo "ec2_ip=$IP" >> $GITHUB_OUTPUT
-    - name: Get Ubuntu Public IP   
-      id: get_ubuntu_ip
-      run: |
-        RAW_OUTPUT=$(terraform output -raw ubuntu_user_public_ip 2>/dev/null)
-        IP=$(echo "$RAW_OUTPUT" | grep -oE '([0-9]{1,3}\.){3}[0-9]{1,3}')
 
-        if [ -z "$IP" ]; then
-        echo "Failed to get a valid Ubuntu IP address from Terraform output"
-        exit 1
-        fi
-
-        echo "ubuntu_ip=$IP" >> $GITHUB_OUTPUT
   ansible_deploy:
     runs-on: ubuntu-latest
     needs: terraform_apply
 
     steps:
-    - name: Checkout Repo
-      uses: actions/checkout@v3
+      - name: Checkout Repo
+        uses: actions/checkout@v3
 
-    - name: Setup SSH Key
-      run: |
-        mkdir -p ~/.ssh
-        echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/id_rsa_github_actions_new
-        chmod 600 ~/.ssh/id_rsa_github_actions_new
+      - name: Setup SSH Key
+        run: |
+          mkdir -p ~/.ssh
+          echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/id_rsa_github_actions_new
+          chmod 600 ~/.ssh/id_rsa_github_actions_new
 
-    - name: Generate dynamic inventory.ini
-      run: |
-        echo "[app]" > inventory.ini
-        echo "${{ needs.terraform_apply.outputs.ec2_ip }} ansible_user=ec2-user ansible_ssh_private_key_file=/home/runner/.ssh/id_rsa_github_actions_new" >> inventory.ini
-        echo "${{ needs.terraform_apply.outputs.ubuntu_ip }} ansible_user=ubuntu ansible_ssh_private_key_file=/home/runner/.ssh/id_rsa_github_actions_new" >> inventory.ini
+      - name: Generate dynamic inventory.ini
+        run: |
+          echo "[app]" > inventory.ini
+          echo "${{ needs.terraform_apply.outputs.ec2_ip }} ansible_user=ec2-user ansible_ssh_private_key_file=/home/runner/.ssh/id_rsa_github_actions_new" >> inventory.ini
 
-    - name: Add EC2 hosts to known_hosts
-      run: |
-        ssh-keyscan -H ${{ needs.terraform_apply.outputs.ec2_ip }} >> ~/.ssh/known_hosts
-        ssh-keyscan -H ${{ needs.terraform_apply.outputs.ubuntu_ip }} >> ~/.ssh/known_hosts
+      - name: Add EC2 hosts to known_hosts
+        run: |
+          ssh-keyscan -H ${{ needs.terraform_apply.outputs.ec2_ip }} >> ~/.ssh/known_hosts
 
-    - name: Install Ansible
-      run: |
-        sudo apt-get update
-        sudo apt-get install -y ansible
+      - name: Install Ansible
+        run: |
+          sudo apt-get update
+          sudo apt-get install -y ansible
 
-    - name: Run Ansible Playbook
-      env:
-        ANSIBLE_HOST_KEY_CHECKING: "False"
-      run: ansible-playbook -i inventory.ini playbook.yml --private-key /home/runner/.ssh/id_rsa_github_actions_new
+      - name: Run Ansible Playbook
+        env:
+          ANSIBLE_HOST_KEY_CHECKING: "False"
+        run: ansible-playbook -i inventory.ini playbook.yml --private-key /home/runner/.ssh/id_rsa_github_actions_new
